apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ambari
spec:
  serviceName: ambari
  replicas: 1
  selector:
    matchLabels:
      run: ambari
  template:
    metadata:
      labels:
        run: ambari
    spec:
      containers:
      - name: ambari
        image: registry.ng.bluemix.net/allianz/ambari:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: web
          - containerPort: 8440
            name: agents
          - containerPort: 8441
            name: agents-sec
        livenessProbe:
          httpGet: 
            path: /
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ambari-web
  labels:
    run: ambari
spec:
  type: NodePort
  selector:
    run: ambari
  ports:
   - protocol: TCP
     port: 8080
     name: web
     nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: ambari
  labels:
    run: ambari
spec:
  type: 
  selector:
    run: ambari
  clusterIP: None
  ports:
   - protocol: TCP
     port: 8440
     name: agents
   - protocol: TCP
     port: 8441
     name: agents-sec
