apiVersion: v1
clusters:
- name: allianz_test
  cluster:
    certificate-authority: ca-prod-dal10-allianz_test.pem
    server: https://169.46.7.238:32577
contexts:
- name: allianz_test
  context:
    cluster: allianz_test
    user: https://iam.ng.bluemix.net/kubernetes#bohdan.bashynskyi@pl.ibm.com
    namespace: default
current-context: allianz_test
kind: Config
users:
- name: https://iam.ng.bluemix.net/kubernetes#bohdan.bashynskyi@pl.ibm.com
  user:
    auth-provider:
      name: oidc
      config:
        client-id: bx
        client-secret: bx
        id-token: eyJraWQiOiIyMDE3MDQwMi0wMDowMDowMCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2lhbS5uZy5ibHVlbWl4Lm5ldC9rdWJlcm5ldGVzIiwic3ViIjoiYm9oZGFuLmJhc2h5bnNreWlAcGwuaWJtLmNvbSIsImF1ZCI6ImJ4IiwiZXhwIjoxNDk2MzEzOTc0LCJpYXQiOjE0OTYzMTAzNzR9.lL0nQKJiK6_VgKrdDJ1Z7ajx7y_yKhZmill5gtTc3X0oaEmOHDpErGZwK32Gc3C9I1r2eH9j1v-NFxlZ3kut3Jhdp7FeECpL3_I6sMsPHm7ca1ZPIlht8uTGPeZeVJ_M7WGonS0ZfYHHTERmSPeWQodoX7VZE1C1z_NJ2xj747X6ut-84YzGOExQBLzThHV0D-Qc9Lo6E4EApoFN8FGflhs3DqHZ4Wp3QdO5HwDmjrGV-DD0PkubbwMz71wqi8gBn2ufJDe3HyPWjFVISUVAjzqCFphvGhFypFXh5JQ1i_wqVbOzMXhrTRl7KRsf3TTtPLjsnA4ANntxMsSA5VzdCQ
        idp-issuer-url: https://iam.ng.bluemix.net/kubernetes
        refresh-token: fKUHZh_FJq9h5s2EYAJHrZa2tSQtqSTM91lS9zJSiX85MhFjpC1DdfC6_gn0CtA9LHMxQBTBmmbihfeZ5acYWlI3GsnRFYa-qinPhmMEbpYbcqx0GTDTuUoLjy7NRyHsrjo81fkH_0e5eBZDGLwsRrrFMmMy8ThzKdftPDYLHCqSb9OAtsyIC0Ez2-Frn-m3s4ZZ38ac79x5b-ToMOpT4hzkxtC0MZ_IIHkdVTFbYSqfpYxBkNsJsQ-XCptMOcGtTg0KKdomvHcJuvL6N_rcry0-py5QTo9ckstqQgK55OpfibeUPvNxcVD3xIzbZnkBTA99ovPf8_G3f2lyrisQGBeBrCXRTDtGpm9sdbZ8d0tIeCe5TaMuonIybBD0n8L_IUzy9J266yQ43NAlgX_9DX9ntIam71TbKBfFVU-FxZZ8J5vvPo-Jyn7fysLPY_QB4a-oGF1__bqvPcBOWbF_4lvjHHWXP-BqSQO-MRTDXWvhtxKpGO4JSt9y0OGt7n9F7a7nGzoRsaRqx7Oy-k-k6hVSO8kEb4pUzP8uzoc7ArTuZVfKY0g3QepEAN7W4tyFDmRfSgc82agtoG5VQUk6ZZwSXa5_8YWI5sEPii3dW8j87UCtdm_rgIXIJihDwVAq
